set(CMAKE_CXX_STANDARD 23)

if("Linux" STREQUAL ${CMAKE_HOST_SYSTEM_NAME})
  add_compile_options(-g)
  add_compile_options(-Wall)
  # add_compile_options(-Werror)
  add_compile_options(-Wno-error=deprecated-declarations)
  add_compile_options(-Wno-deprecated-declarations)
  add_compile_options(-Wno-attributes)
endif()
