set(DAWN_FETCH_DEPENDENCIES ON)
set(DAWN_BUILD_MONOLITHIC_LIBRARY OFF)

if("Windows" STREQUAL ${CMAKE_HOST_SYSTEM_NAME})
  set(DAWN_USE_BUILT_DXC
      ON
      CACHE BOOL "" FORCE)
endif()

set(DAWN_ENABLE_VULKAN ON)
set(DAWN_ENABLE_NULL OFF)
set(DAWN_ENABLE_D3D11 OFF)
set(DAWN_ENABLE_OPENGLES OFF)
set(DAWN_ENABLE_DESKTOP_GL OFF)
